version: '3'
services:
  web: &web 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    command: uvicorn app:app --reload --workers 4 --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama
    ports:
      - 11434:11434